import type {
  CredentialReceipt,
  DataSystem,
  PrivacyRequest,
  WorkspaceState,
} from '@/types/domain'
import { addDays, buildWorkflowSteps } from './workflow'
import { credentialDigest, credentialKey, ignoreReasons } from './credentials'

function receipt(
  id: string,
  fields: Omit<CredentialReceipt, 'id' | 'credentialKey' | 'credentialDigest'>,
): CredentialReceipt {
  return {
    id,
    credentialKey: credentialKey(fields.credentialRef, fields.batch),
    credentialDigest: credentialDigest(fields.credentialRef, fields.batch),
    ...fields,
  }
}

const systems: DataSystem[] = [
  {
    id: 'sys-crm',
    name: '客户关系管理系统',
    owner: '客户平台组',
    dataDomain: '客户身份、联系信息、服务记录',
    transferMethod: '受控接口导出',
    slaDays: 5,
    requestTypes: ['access', 'rectification', 'deletion', 'restriction'],
    status: 'active',
  },
  {
    id: 'sys-order',
    name: '订单与交易平台',
    owner: '交易系统组',
    dataDomain: '订单、支付标识、收货信息',
    transferMethod: '离线加密包',
    slaDays: 7,
    requestTypes: ['access', 'deletion'],
    status: 'active',
  },
  {
    id: 'sys-marketing',
    name: '营销自动化平台',
    owner: '增长技术组',
    dataDomain: '同意记录、标签、触达历史',
    transferMethod: '消息队列同步',
    slaDays: 3,
    requestTypes: ['access', 'deletion', 'withdraw-consent', 'restriction'],
    status: 'active',
  },
  {
    id: 'sys-archive',
    name: '电子档案库',
    owner: '档案管理组',
    dataDomain: '合同、凭证、历史记录',
    transferMethod: '双人复核导出',
    slaDays: 10,
    requestTypes: ['access', 'rectification', 'restriction'],
    status: 'maintenance',
  },
  {
    id: 'sys-support',
    name: '客服工单系统',
    owner: '服务运营组',
    dataDomain: '沟通记录、身份核验材料、附件',
    transferMethod: '脱敏下载',
    slaDays: 5,
    requestTypes: ['access', 'rectification', 'deletion', 'restriction'],
    status: 'active',
  },
  {
    id: 'sys-risk',
    name: '风控决策平台',
    owner: '风险技术组',
    dataDomain: '设备指纹、风险标签、决策结果',
    transferMethod: '隔离区核验',
    slaDays: 8,
    requestTypes: ['access', 'rectification', 'restriction'],
    status: 'active',
  },
]

function audit(
  id: string,
  action: string,
  operator: string,
  detail: string,
  createdAt: string,
) {
  return { id, action, operator, detail, createdAt }
}

export function createInitialState(): WorkspaceState {
  const request1At = '2026-09-25T02:30:00.000Z'
  const request2At = '2026-09-18T06:20:00.000Z'
  const request3At = '2026-09-21T03:10:00.000Z'
  const request4At = '2026-09-24T05:40:00.000Z'
  const request5At = '2026-09-05T01:00:00.000Z'
  const request1Due = addDays(new Date(request1At), 30).toISOString()
  const request2Due = addDays(new Date(request2At), 30).toISOString()
  const request3Due = addDays(new Date(request3At), 45).toISOString()
  const request4Due = addDays(new Date(request4At), 30).toISOString()
  const request5Due = addDays(new Date(request5At), 30).toISOString()

  const requests: PrivacyRequest[] = [
    {
      id: 'req-001',
      code: 'DSR-2026-001',
      requesterName: '张晨',
      requesterContact: 'zh***@example.com',
      region: 'cn',
      type: 'access',
      status: 'processing',
      identity: {
        status: 'verified',
        materialType: 'masked-id',
        maskedReference: '310***********1234',
        protectedDigest: 'ID-74A1B2',
        note: '证件影像已核验，原始文件未进入业务库。',
        reviewedAt: '2026-09-25T04:10:00.000Z',
      },
      requestedAt: request1At,
      dueAt: request1Due,
      extendedDays: 0,
      affectedSystemIds: ['sys-crm', 'sys-order', 'sys-support'],
      tasks: buildWorkflowSteps({
        requestId: 'req-001',
        type: 'access',
        systemIds: ['sys-crm', 'sys-order', 'sys-support'],
        requestedAt: request1At,
        dueAt: request1Due,
        initialStatus: 'processing',
        systems,
      }),
      evidence: [
        {
          id: 'evidence-001-a',
          stepId: 'req-001-identity',
          name: '身份核验记录',
          evidenceType: 'signed-record',
          digest: '9A11-77D2',
          uploadedBy: '当前客服',
          uploadedAt: '2026-09-25T04:10:00.000Z',
          protected: true,
        },
      ],
      systemFulfillments: [
        {
          systemId: 'sys-crm',
          state: 'confirmed',
          batchSeq: 1,
          attempts: 1,
          lastSuccessReceiptId: 'receipt-001-crm-1',
          confirmedAt: '2026-09-27T02:00:00.000Z',
          confirmedBy: '隐私运营',
          lastFailureReason: '',
          retries: [],
          receipts: [
            receipt('receipt-001-crm-1', {
              systemId: 'sys-crm',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'success',
              status: 'accepted',
              reason: '',
              credentialRef: 'CRM-ACCESS-RCP-7721',
              detail: '客户资料导出回执，访问包已入受控区。',
              receivedAt: '2026-09-26T08:00:00.000Z',
              receivedBy: '客户平台组',
            }),
            receipt('receipt-001-crm-2', {
              systemId: 'sys-crm',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'success',
              status: 'ignored',
              reason: ignoreReasons.duplicate('2026-09-26T08:00:00.000Z'),
              credentialRef: 'CRM-ACCESS-RCP-7721',
              detail: '接口重发同一回执。',
              receivedAt: '2026-09-26T10:30:00.000Z',
              receivedBy: '客户平台组',
            }),
          ],
        },
        {
          systemId: 'sys-order',
          state: 'failed',
          batchSeq: 2,
          attempts: 2,
          lastSuccessReceiptId: undefined,
          lastFailureAt: '2026-09-29T06:10:00.000Z',
          lastFailureReason: '加密导出任务校验失败：支付标识字段缺失。',
          retries: [
            {
              round: 2,
              batch: '批次 2',
              reason: '首次导出字段校验失败，按原系统重新发起。',
              retriedAt: '2026-09-28T12:00:00.000Z',
              retriedBy: '交易系统组',
            },
          ],
          receipts: [
            receipt('receipt-001-order-1', {
              systemId: 'sys-order',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'failure',
              status: 'accepted',
              reason: '',
              credentialRef: 'ORDER-JOB-FAIL-3042',
              detail: '离线加密包生成超时。',
              receivedAt: '2026-09-27T09:00:00.000Z',
              receivedBy: '交易系统组',
            }),
            receipt('receipt-001-order-2', {
              systemId: 'sys-order',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'failure',
              status: 'ignored',
              reason: ignoreReasons.duplicate('2026-09-27T09:00:00.000Z'),
              credentialRef: 'ORDER-JOB-FAIL-3042',
              detail: '失败通知重复推送。',
              receivedAt: '2026-09-27T09:05:00.000Z',
              receivedBy: '交易系统组',
            }),
            receipt('receipt-001-order-3', {
              systemId: 'sys-order',
              batch: '批次 2',
              batchSeq: 2,
              outcome: 'failure',
              status: 'accepted',
              reason: '',
              credentialRef: 'ORDER-JOB-FAIL-3108',
              detail: '加密导出任务校验失败：支付标识字段缺失。',
              receivedAt: '2026-09-29T06:10:00.000Z',
              receivedBy: '交易系统组',
            }),
            receipt('receipt-001-order-4', {
              systemId: 'sys-order',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'success',
              status: 'ignored',
              reason: ignoreReasons.staleBatch(2),
              credentialRef: 'ORDER-LATE-RCP-2999',
              detail: '旧批次离线包迟到，当前已在批次 2 重试。',
              receivedAt: '2026-09-30T01:20:00.000Z',
              receivedBy: '交易系统组',
            }),
          ],
        },
        {
          systemId: 'sys-support',
          state: 'pending',
          batchSeq: 1,
          attempts: 1,
          lastFailureReason: '',
          retries: [],
          receipts: [],
        },
      ],
      fulfillmentDiscrepancies: [],
      conflicts: [],
      resultSummary: '',
      closureReason: '',
      audit: [
        audit(
          'req-audit-001',
          '登记请求',
          '客服专员',
          '访问请求已登记，并生成 30 日流程。',
          request1At,
        ),
      ],
    },
    {
      id: 'req-002',
      code: 'DSR-2026-002',
      requesterName: '王宁',
      requesterContact: 'wa***@example.com',
      region: 'eu',
      type: 'deletion',
      status: 'review-required',
      identity: {
        status: 'insufficient',
        materialType: 'authorization-letter',
        maskedReference: '授权书仅含截图',
        protectedDigest: 'AUTH-11E9',
        note: '缺少委托关系证明，需进入身份材料复核。',
      },
      requestedAt: request2At,
      dueAt: request2Due,
      extendedDays: 0,
      duplicateOf: 'req-005',
      affectedSystemIds: ['sys-crm', 'sys-marketing', 'sys-support'],
      tasks: buildWorkflowSteps({
        requestId: 'req-002',
        type: 'deletion',
        systemIds: ['sys-crm', 'sys-marketing', 'sys-support'],
        requestedAt: request2At,
        dueAt: request2Due,
        initialStatus: 'review-required',
        systems,
      }),
      evidence: [],
      systemFulfillments: [
        {
          systemId: 'sys-crm',
          state: 'pending',
          batchSeq: 1,
          attempts: 1,
          lastFailureReason: '',
          receipts: [],
          retries: [],
        },
        {
          systemId: 'sys-marketing',
          state: 'pending',
          batchSeq: 1,
          attempts: 1,
          lastFailureReason: '',
          receipts: [],
          retries: [],
        },
        {
          systemId: 'sys-support',
          state: 'pending',
          batchSeq: 1,
          attempts: 1,
          lastFailureReason: '',
          receipts: [],
          retries: [],
        },
      ],
      fulfillmentDiscrepancies: [],
      conflicts: [
        '身份材料不足：授权书无法证明申请人与数据主体关系。',
        '疑似重复请求：与 DSR-2026-005 的请求人和处理类型相同。',
      ],
      resultSummary: '',
      closureReason: '',
      audit: [
        audit(
          'req-audit-002',
          '转入复核队列',
          '隐私运营',
          '身份材料不足且检测到疑似重复请求。',
          '2026-09-19T02:00:00.000Z',
        ),
      ],
    },
    {
      id: 'req-003',
      code: 'DSR-2026-003',
      requesterName: '刘晓',
      requesterContact: 'li***@example.com',
      region: 'us',
      type: 'rectification',
      status: 'review-required',
      identity: {
        status: 'verified',
        materialType: 'account-ownership',
        maskedReference: '账号所有权验证通过',
        protectedDigest: 'ACC-559A',
        note: '依据登录挑战与近期交易完成核验。',
        reviewedAt: '2026-09-21T05:30:00.000Z',
      },
      requestedAt: request3At,
      dueAt: request3Due,
      extendedDays: 0,
      affectedSystemIds: ['sys-crm', 'sys-risk', 'sys-support'],
      tasks: buildWorkflowSteps({
        requestId: 'req-003',
        type: 'rectification',
        systemIds: ['sys-crm', 'sys-risk', 'sys-support'],
        requestedAt: request3At,
        dueAt: request3Due,
        initialStatus: 'processing',
        systems,
      }).map((step, index) => (index === 1 ? { ...step, status: 'blocked', exceptionReason: '风控平台返回值与客服系统不一致。' } : step)),
      evidence: [],
      systemFulfillments: [
        {
          systemId: 'sys-crm',
          state: 'confirmed',
          batchSeq: 1,
          attempts: 1,
          lastSuccessReceiptId: 'receipt-003-crm-1',
          confirmedAt: '2026-09-27T03:00:00.000Z',
          confirmedBy: '隐私运营',
          lastFailureReason: '',
          retries: [],
          receipts: [
            receipt('receipt-003-crm-1', {
              systemId: 'sys-crm',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'success',
              status: 'accepted',
              reason: '',
              credentialRef: 'CRM-RECT-RCP-5540',
              detail: '姓名更正已生效并返回变更后记录。',
              receivedAt: '2026-09-27T01:00:00.000Z',
              receivedBy: '客户平台组',
            }),
          ],
        },
        {
          systemId: 'sys-risk',
          state: 'failed',
          batchSeq: 1,
          attempts: 1,
          lastFailureAt: '2026-09-28T08:20:00.000Z',
          lastFailureReason: '风险标签关联姓名属于反欺诈保留范围，拒绝更新。',
          retries: [],
          receipts: [
            receipt('receipt-003-risk-1', {
              systemId: 'sys-risk',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'failure',
              status: 'accepted',
              reason: '',
              credentialRef: 'RISK-RECT-DENY-1187',
              detail: '风险标签关联姓名属于反欺诈保留范围，拒绝更新。',
              receivedAt: '2026-09-28T08:20:00.000Z',
              receivedBy: '风险技术组',
            }),
          ],
        },
        {
          systemId: 'sys-support',
          state: 'succeeded',
          batchSeq: 1,
          attempts: 1,
          lastSuccessReceiptId: 'receipt-003-support-1',
          lastFailureReason: '',
          retries: [],
          receipts: [
            receipt('receipt-003-support-1', {
              systemId: 'sys-support',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'success',
              status: 'accepted',
              reason: '',
              credentialRef: 'SUPPORT-RECT-RCP-2260',
              detail: '工单与沟通记录中的称呼已更正。',
              receivedAt: '2026-09-27T07:40:00.000Z',
              receivedBy: '服务运营组',
            }),
          ],
        },
      ],
      fulfillmentDiscrepancies: [
        {
          id: 'discrepancy-003-1',
          systemId: 'sys-risk',
          kind: 'content-mismatch',
          description: '风控平台保留旧值，与客户、客服系统的更正结果不一致，需要确认例外是否合法。',
          raisedAt: '2026-09-28T08:30:00.000Z',
          raisedBy: '数据管理员',
          status: 'open',
          resolution: '',
        },
      ],
      conflicts: ['跨系统结果冲突：客户系统中的姓名已更正，但风控平台仍保留旧值。'],
      resultSummary: '',
      closureReason: '',
      audit: [
        audit(
          'req-audit-003',
          '发现跨系统冲突',
          '数据管理员',
          '风控平台拒绝更新风险标签关联姓名。',
          '2026-09-28T08:30:00.000Z',
        ),
      ],
    },
    {
      id: 'req-004',
      code: 'DSR-2026-004',
      requesterName: '陈妙',
      requesterContact: 'ch***@example.com',
      region: 'sg',
      type: 'withdraw-consent',
      status: 'pending-close',
      identity: {
        status: 'verified',
        materialType: 'account-ownership',
        maskedReference: '账号所有权验证通过',
        protectedDigest: 'ACC-880D',
        note: '账号双因素验证通过。',
        reviewedAt: '2026-09-24T07:00:00.000Z',
      },
      requestedAt: request4At,
      dueAt: request4Due,
      extendedDays: 0,
      affectedSystemIds: ['sys-marketing'],
      tasks: buildWorkflowSteps({
        requestId: 'req-004',
        type: 'withdraw-consent',
        systemIds: ['sys-marketing'],
        requestedAt: request4At,
        dueAt: request4Due,
        initialStatus: 'pending-close',
        systems,
      }),
      evidence: [
        {
          id: 'evidence-004-a',
          stepId: 'req-004-execute-sys-marketing',
          name: '同意状态变更日志',
          evidenceType: 'execution-log',
          digest: 'E31A-880D',
          uploadedBy: '增长技术组',
          uploadedAt: '2026-09-28T09:00:00.000Z',
          protected: true,
        },
      ],
      systemFulfillments: [
        {
          systemId: 'sys-marketing',
          state: 'confirmed',
          batchSeq: 1,
          attempts: 1,
          lastSuccessReceiptId: 'receipt-004-mkt-1',
          confirmedAt: '2026-09-28T09:05:00.000Z',
          confirmedBy: '隐私运营',
          lastFailureReason: '',
          retries: [],
          receipts: [
            receipt('receipt-004-mkt-1', {
              systemId: 'sys-marketing',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'success',
              status: 'accepted',
              reason: '',
              credentialRef: 'MKT-CONSENT-WD-9032',
              detail: '同意状态已置为撤回，自动化触达已停止。',
              receivedAt: '2026-09-28T09:00:00.000Z',
              receivedBy: '增长技术组',
            }),
            receipt('receipt-004-mkt-2', {
              systemId: 'sys-marketing',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'success',
              status: 'ignored',
              reason: ignoreReasons.duplicate('2026-09-28T09:00:00.000Z'),
              credentialRef: 'MKT-CONSENT-WD-9032',
              detail: '消息队列至少一次投递导致重复送达。',
              receivedAt: '2026-09-28T09:42:00.000Z',
              receivedBy: '增长技术组',
            }),
            receipt('receipt-004-mkt-3', {
              systemId: 'sys-marketing',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'success',
              status: 'ignored',
              reason: ignoreReasons.confirmed('2026-09-28T09:05:00.000Z'),
              credentialRef: 'MKT-LATE-RCP-9041',
              detail: '确认后通道补推的回执，仅留档不回退。',
              receivedAt: '2026-09-29T02:00:00.000Z',
              receivedBy: '增长技术组',
            }),
          ],
        },
      ],
      fulfillmentDiscrepancies: [],
      conflicts: [],
      resultSummary: '营销平台已撤回同意并停止后续自动化触达。',
      closureReason: '',
      audit: [
        audit(
          'req-audit-004',
          '待关闭复核',
          '隐私运营',
          '全部系统任务已完成，等待负责人确认结果。',
          '2026-09-28T09:10:00.000Z',
        ),
      ],
    },
    {
      id: 'req-005',
      code: 'DSR-2026-005',
      requesterName: '王宁',
      requesterContact: 'wa***@example.com',
      region: 'eu',
      type: 'deletion',
      status: 'completed',
      identity: {
        status: 'verified',
        materialType: 'masked-id',
        maskedReference: '310***********8832',
        protectedDigest: 'ID-771B',
        note: '身份核验已完成。',
        reviewedAt: '2026-09-05T03:30:00.000Z',
      },
      requestedAt: request5At,
      dueAt: request5Due,
      extendedDays: 0,
      affectedSystemIds: ['sys-crm', 'sys-marketing'],
      tasks: buildWorkflowSteps({
        requestId: 'req-005',
        type: 'deletion',
        systemIds: ['sys-crm', 'sys-marketing'],
        requestedAt: request5At,
        dueAt: request5Due,
        initialStatus: 'completed',
        systems,
      }),
      evidence: [
        {
          id: 'evidence-005-a',
          stepId: 'req-005-execute-sys-crm',
          name: '删除执行回执',
          evidenceType: 'system-response',
          digest: 'E5A0-1201',
          uploadedBy: '客户平台组',
          uploadedAt: '2026-09-08T05:00:00.000Z',
          protected: true,
        },
      ],
      systemFulfillments: [
        {
          systemId: 'sys-crm',
          state: 'confirmed',
          batchSeq: 1,
          attempts: 1,
          lastSuccessReceiptId: 'receipt-005-crm-1',
          confirmedAt: '2026-09-09T03:00:00.000Z',
          confirmedBy: '隐私负责人',
          lastFailureReason: '',
          retries: [],
          receipts: [
            receipt('receipt-005-crm-1', {
              systemId: 'sys-crm',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'success',
              status: 'accepted',
              reason: '',
              credentialRef: 'CRM-DELETE-RCP-1201',
              detail: '客户身份与服务记录已删除并返回最小合规凭证。',
              receivedAt: '2026-09-08T05:00:00.000Z',
              receivedBy: '客户平台组',
            }),
          ],
        },
        {
          systemId: 'sys-marketing',
          state: 'confirmed',
          batchSeq: 1,
          attempts: 1,
          lastSuccessReceiptId: 'receipt-005-mkt-1',
          confirmedAt: '2026-09-09T03:00:00.000Z',
          confirmedBy: '隐私负责人',
          lastFailureReason: '',
          retries: [],
          receipts: [
            receipt('receipt-005-mkt-1', {
              systemId: 'sys-marketing',
              batch: '批次 1',
              batchSeq: 1,
              outcome: 'success',
              status: 'accepted',
              reason: '',
              credentialRef: 'MKT-DELETE-RCP-3320',
              detail: '标签与触达历史已删除，同意记录保留法定最小副本。',
              receivedAt: '2026-09-08T11:20:00.000Z',
              receivedBy: '增长技术组',
            }),
          ],
        },
      ],
      fulfillmentDiscrepancies: [],
      conflicts: [],
      resultSummary: '已完成请求主体在两个系统中的删除，并保留最小合规凭证。',
      closureReason: '期限已到且任务完整，经复核后关闭。',
      audit: [
        audit(
          'req-audit-005',
          '完成请求',
          '隐私负责人',
          '处理结果合并完成并生成操作审计。',
          '2026-09-10T02:00:00.000Z',
        ),
      ],
    },
  ]

  return {
    requests,
    systems,
    comments: [
      {
        id: 'comment-001',
        requestId: 'req-003',
        author: '风控平台管理员',
        content: '风险标签属于反欺诈例外审查范围，不能直接按普通资料更正。',
        createdAt: '2026-09-28T08:35:00.000Z',
      },
      {
        id: 'comment-002',
        requestId: 'req-002',
        author: '隐私运营',
        content: '请先确认该请求与 DSR-2026-005 是否属于重复申请。',
        createdAt: '2026-09-19T02:05:00.000Z',
      },
    ],
    audit: [
      {
        id: 'audit-global-1',
        requestId: 'req-001',
        action: '登记请求',
        operator: '客服专员',
        detail: '访问请求进入 30 日履约流程。',
        createdAt: request1At,
      },
      {
        id: 'audit-global-2',
        requestId: 'req-002',
        action: '身份材料复核',
        operator: '隐私运营',
        detail: '身份材料不足并检测到疑似重复请求。',
        createdAt: '2026-09-19T02:00:00.000Z',
      },
      {
        id: 'audit-global-3',
        requestId: 'req-003',
        action: '跨系统结果冲突',
        operator: '数据管理员',
        detail: '风控平台与客户系统结果不一致，进入复核队列。',
        createdAt: '2026-09-28T08:30:00.000Z',
      },
    ],
    revision: 1,
  }
}

export const requestTypeOptions = [
  { value: 'access', label: '访问' },
  { value: 'rectification', label: '更正' },
  { value: 'deletion', label: '删除' },
  { value: 'withdraw-consent', label: '撤回同意' },
  { value: 'restriction', label: '限制处理' },
] as const
